import { Component, OnInit } from '@angular/core';

@Component({
	selector: 'todo-input',
	template: `
	<input [value]="generateTitle()">
		<button>Save</button>
	<p>The title is: {{ title }}</p>
	`,
	styleUrls: ['./input.component.css']
})

export class InputComponent implements OnInit {
	title: string = 'My First Todo Title !!!';           

	constructor() { }                     

	ngOnInit() {
		setTimeout(() => {
			this.title = 'This is not the title you are looking for';  
		}, 3000);
	}
	
	generateTitle(): string {
		return 'This title was generated by a method.';
	}

}